package org.example.HW21.entity.enumeration;

public enum OrderStatus {
    WAITING_FOR_THE_SUGGESTION_OF_EXPERTS,
    WAITING_FOR_SPECIALIST_SELECTION,
    WAITING_FOR_THE_SPECIALIST_TO_COME_TO_YOUR_PLACE,
    STARTED,
    DONE,
    PAID
}
